FROM node:16 AS client
WORKDIR /app
COPY client/package.json client/package-lock.json ./
RUN npm install
COPY client .
RUN npm run build

FROM node:16
WORKDIR /app
COPY server/package.json server/package-lock.json ./
RUN npm install
RUN npm install knex -g
COPY server .
COPY --from=client /app/build public
COPY start-server.sh /app/
EXPOSE 3333
ENTRYPOINT bash start-server.sh