FROM node:14 AS client
WORKDIR /app
COPY client/package.json client/package-lock.json .
RUN npm install
COPY client .
RUN npm run build

FROM node:14
WORKDIR /app
COPY server/package.json server/package-lock.json .
RUN npm install
RUN npm install knex -g
COPY server .
COPY --from=client /app/build public
EXPOSE 3333
RUN knex migrate:latest
RUN knex seed:run
RUN npm run start

