FROM node:10 AS client
WORKDIR client
COPY ./package.json ./package-lock.lock 

COPY ./ ./
RUN npm install 
# 
RUN npm run build --production

FROM node:10
WORKDIR server
COPY ./package.json ./package-lock.json 
RUN npm install
# COPY server .
COPY --from=client /client/build/* ./
EXPOSE 5000
CMD ["node", "www/main.js"]