version: "3"
services:
  # postgres_db:
  #   container_name: postgres_db
  #   image: "postgres:latest"
  #   environment:
  #   - POSTGRES_USER=payengineuser
  #   - POSTGRES_PASSWORD=payenginepassword
  #   - POSTGRES_DB=payengine
  #   ports:
  #   - 5433:5432

  server:
    container_name: server
    # depends_on:
    #   - postgres_db
    build:
      dockerfile: DockerFile
      context: "./"

    #  volumes:
    #    - /app/node_modules
    #    - ./server:/app
    # environment:
    #   DATABASE_URL: google.com
    #   DATABASE_USERNAME: payengineuser
    #   DATABASE_PASSWORD: payenginepassword
    #   DATABASE_PORT: 5433
    #   DATABASE_NAME: payengine
    env_file: server/.env
    ports:
      - 3333:3333
